# Generated by Django 4.2 on 2024-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='occupation',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(choices=[('user', 'user'), ('staff', 'staff'), ('excutive', 'excutive')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='D_O_B',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
