# Generated by Django 4.2 on 2024-08-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_status',
            field=models.CharField(choices=[('User', 'User'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Executive', 'Executive')], max_length=255),
        ),
    ]
