# Generated by Django 4.2 on 2024-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ID_Number',
            field=models.CharField(max_length=20),
        ),
    ]
