# Generated by Django 4.2 on 2024-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ID_Number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
