# Generated by Django 4.2 on 2024-08-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type_of_customer', models.CharField(choices=[('Individual', 'Individual'), ('Cooperate', 'Cooperate')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0.0)),
                ('total_amount', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('quantity', models.IntegerField(default=0.0)),
                ('stock_brought_in', models.IntegerField(default=0)),
                ('price', models.FloatField(default=0.0)),
                ('project', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateTimeField(auto_now_add=True)),
                ('sale_id', models.CharField(default='', max_length=255)),
                ('sale_details', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0.0)),
                ('branch', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='transactions.stock')),
            ],
        ),
    ]
