# Generated by Django 4.2 on 2024-08-14 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('price', models.FloatField(default=0.0)),
                ('branch', models.CharField(max_length=255)),
                ('project', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_sale', models.DateTimeField(auto_now_add=True)),
                ('sale_details', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0.0)),
                ('sales_rep', models.CharField(max_length=255)),
                ('branch', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='transactions.stock')),
            ],
        ),
    ]
