# Generated by Django 4.2 on 2024-08-15 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type_of_customer', models.CharField(choices=[('Individual', 'Individual'), ('Cooperate', 'Cooperate')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='stock',
            name='branch',
        ),
        migrations.AddField(
            model_name='sales',
            name='sale_id',
            field=models.CharField(default='M000', max_length=255),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='stock_brought_in',
            field=models.IntegerField(default=0),
        ),
    ]
