# Generated by Django 4.2 on 2024-08-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_customer_remove_stock_branch_sales_sale_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('details', models.TextField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('unit_price', models.IntegerField(default=0.0)),
                ('total_amount', models.IntegerField(default=0.0)),
            ],
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
