# Generated by Django 4.2 on 2024-08-19 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_sales_sales_rep'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='sales_rep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.customer'),
        ),
    ]
