# Generated by Django 4.2 on 2024-08-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_remove_stock_assets_alter_stock_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='stock_brought_in',
            new_name='new_stock',
        ),
    ]
