# Generated by Django 4.2 on 2024-08-20 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_debitors_debt_source'),
        ('transactions', '0006_rename_stock_brought_in_stock_new_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='stock',
        ),
        migrations.AlterField(
            model_name='sales',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.stock'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.staff'),
        ),
    ]
