# Generated by Django 4.2 on 2024-08-20 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_branch_branch_supervisor'),
        ('transactions', '0007_remove_sales_stock_alter_sales_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.branch'),
        ),
    ]
