# Generated by Django 4.2 on 2024-08-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_rename_creditor_name_liabilities_creditor_name'),
        ('transactions', '0008_alter_sales_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type_of_supplier', models.CharField(choices=[('Individual', 'Individual'), ('Cooperate', 'Cooperate')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='company.organisation')),
            ],
        ),
    ]
