# Generated by Django 4.2 on 2024-08-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supply',
            field=models.CharField(default='', max_length=255),
        ),
    ]
