# Generated by Django 4.2 on 2024-08-20 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_suppliers_liabilities_supplier_and_more'),
        ('transactions', '0010_supplier_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='liabilities',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.liabilities'),
        ),
    ]
