# Generated by Django 4.2 on 2024-08-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_sales_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='sales_rep',
        ),
    ]
