# Generated by Django 4.2 on 2024-08-24 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_alter_companyregistration_motive'),
        ('transactions', '0014_remove_sales_customer_remove_sales_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='transactions.customer'),
        ),
        migrations.AddField(
            model_name='sales',
            name='sales_rep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.staff'),
        ),
    ]
