# Generated by Django 4.2 on 2024-08-27 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_remove_assets_asset_acquisition_date_and_more'),
        ('transactions', '0015_sales_customer_sales_sales_rep'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.projects'),
        ),
    ]
