# Generated by Django 4.2 on 2024-08-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_rename_company_description_organisation_organisation_description'),
        ('transactions', '0016_sales_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='company.projects'),
        ),
    ]
