# Generated by Django 4.2 on 2024-08-27 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_rename_company_description_organisation_organisation_description'),
        ('transactions', '0017_alter_sales_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.branch'),
        ),
        migrations.AddField(
            model_name='stock',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.company'),
        ),
    ]
