# Generated by Django 4.2 on 2024-09-01 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_rename_purchase_details_purchases_details_and_more'),
        ('transactions', '0023_delete_product_rename_product_project_stock_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.assets'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='product_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
