# Generated by Django 4.2 on 2024-09-01 04:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_stock_asset_alter_stock_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
