# Generated by Django 4.2 on 2024-09-11 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_alter_purchased_item_quantity_and_more'),
        ('transactions', '0027_sales_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='company.organisation'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales_item', to='transactions.stock'),
        ),
    ]
