# Generated by Django 4.2 on 2024-09-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_saleitem_returned_saleitem_returned_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
    ]
