# Generated by Django 4.2 on 2024-09-22 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0068_asset_creditor_debtor_remove_assets_branch_and_more'),
        ('transactions', '0030_alter_customer_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='company',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='new_stock',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.organisation'),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='asset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.asset'),
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
    ]
