# Generated by Django 4.2 on 2024-09-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_creditor_credit_amount_paid_and_more'),
        ('transactions', '0031_remove_sales_branch_remove_stock_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='processing_fee',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='sales',
            name='tax_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='company.projects'),
        ),
    ]
