# Generated by Django 4.2 on 2024-08-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_accusation_date', models.DateField(default='2024-08-10')),
                ('asset_name', models.CharField(max_length=255)),
                ('type_of_asset', models.CharField(max_length=255)),
                ('asset_price', models.IntegerField(default=0)),
                ('asset_source', models.CharField(max_length=255)),
                ('depreciation_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('capital', models.IntegerField(default=0.0)),
                ('branches', models.CharField(max_length=255)),
                ('employees', models.IntegerField(default=0)),
                ('projects', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Debitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debit_accusation_date', models.DateField(default='2024-08-10')),
                ('debitor_name', models.CharField(max_length=255)),
                ('type_of_debit', models.CharField(max_length=255)),
                ('debit_source', models.CharField(max_length=255)),
                ('debited_amount', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Liabilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liablity_accusation_date', models.DateField(default='2024-08-10')),
                ('liability_name', models.CharField(max_length=255)),
                ('type_of_liability', models.CharField(max_length=255)),
                ('liability_source', models.CharField(max_length=255)),
                ('liability_amount', models.IntegerField(default=0)),
                ('interest_rate', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(default='2024-08-10')),
                ('project_name', models.CharField(max_length=255)),
                ('project_id', models.CharField(max_length=255)),
                ('project_supervisor', models.CharField(max_length=255)),
                ('employees', models.IntegerField(default=0)),
                ('cash_in_hand', models.IntegerField(default=0)),
                ('project_location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.CharField(max_length=255)),
                ('staff_name', models.CharField(max_length=255)),
                ('staff_salary', models.IntegerField(default=0)),
                ('staff_branch', models.CharField(max_length=255)),
                ('department', models.CharField(choices=[('Sales and Marketing', 'Sales and Marketing'), ('IT', 'IT'), ('Finance', 'Finance'), ('Administration and Development', 'Administration and Development'), ('Other', 'Other'), ('Not Applicable', 'Not Applicable')], max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('occupation', models.CharField(choices=[('Junior', 'Junior'), ('Customer', 'Customer'), ('Senior', 'Senior'), ('Cashier', 'Cashier'), ('Field Employee', 'Field Employee'), ('Manager', 'Manager'), ('CEO', 'CEO'), ('Software Developer', 'Software Developer'), ('Other', 'Other')], max_length=255)),
            ],
        ),
    ]
