# Generated by Django 4.2 on 2024-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_location',
            new_name='branch_name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='employees',
            new_name='no_staff',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_locations',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
