# Generated by Django 4.2 on 2024-08-20 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='projects',
        ),
        migrations.AddField(
            model_name='assets',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.projects'),
        ),
        migrations.AddField(
            model_name='company',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.organisation'),
        ),
        migrations.AddField(
            model_name='debitors',
            name='assets',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.assets'),
        ),
        migrations.AddField(
            model_name='liabilities',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.projects'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projects',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.company'),
        ),
        migrations.AddField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AddField(
            model_name='staff',
            name='customuser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='assets',
            name='asset_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='branches',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='debitors',
            name='debitor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='debitors',
            name='debt_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='debitors',
            name='type_of_debt',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='Creditor_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='liability_source',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='headquaters',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='branch_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_supervisor',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_branch',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
