# Generated by Django 4.2 on 2024-08-12 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_rename_project_location_projects_branch_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_locations',
            new_name='project_location',
        ),
    ]
