# Generated by Django 4.2 on 2024-08-20 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_remove_organisation_company_organisation_founder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='branch_name',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='company',
            name='branches',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='company',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_location',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_supervisor',
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(default='', max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('branch_supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.company')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='company.branch'),
        ),
    ]
