# Generated by Django 4.2 on 2024-08-20 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0004_rename_branch_name_projects_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='supervisor',
        ),
        migrations.AddField(
            model_name='projects',
            name='project_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
