# Generated by Django 4.2 on 2024-08-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_rename_asset_accusation_date_assets_asset_acquisition_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='id',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
