# Generated by Django 4.2 on 2024-08-20 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0005_remove_projects_supervisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='customuser',
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
