# Generated by Django 4.2 on 2024-08-20 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_remove_staff_customuser_alter_staff_staff_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='staff_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='company.branch'),
        ),
    ]
