# Generated by Django 4.2 on 2024-08-20 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_customer_company_customer_organisation'),
        ('company', '0007_alter_staff_staff_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitors',
            name='debitor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='debitors', to='transactions.customer'),
        ),
        migrations.AlterField(
            model_name='debitors',
            name='type_of_debt',
            field=models.CharField(choices=[('', ''), ('Short Term', 'Short Term'), ('Long Term', 'Long Term')], default='', max_length=255),
        ),
    ]
