# Generated by Django 4.2 on 2024-08-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_debitors_debitor_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='debitors',
            name='debt_source',
        ),
    ]
