# Generated by Django 4.2 on 2024-08-20 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_alter_branch_branch_supervisor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liabilities',
            old_name='Creditor_name',
            new_name='creditor_name',
        ),
    ]
