# Generated by Django 4.2 on 2024-08-20 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_supplier'),
        ('company', '0011_rename_creditor_name_liabilities_creditor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilities',
            name='suppliers',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='transactions.supplier'),
        ),
    ]
