# Generated by Django 4.2 on 2024-08-20 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_suppliers_liabilities_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='capital',
            new_name='starting_capital',
        ),
    ]
