# Generated by Django 4.2 on 2024-08-20 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_rename_capital_company_starting_capital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='company.company'),
        ),
    ]
