# Generated by Django 4.2 on 2024-08-20 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_alter_staff_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='company.company'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.branch'),
        ),
    ]
