# Generated by Django 4.2 on 2024-08-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_companyregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyregistration',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='company_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='motive',
            field=models.CharField(default='', max_length=255),
        ),
    ]
