# Generated by Django 4.2 on 2024-08-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_alter_companyregistration_motive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='organisation_phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
