# Generated by Django 4.2 on 2024-08-27 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_purchases_organisation_organisation_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyregistration',
            old_name='address',
            new_name='personal_address',
        ),
        migrations.AddField(
            model_name='assets',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.branch'),
        ),
        migrations.AddField(
            model_name='branch',
            name='branch_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='CEO_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_name_email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='company_phone_number',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='company',
            name='main_branch_location',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='organisation_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyregistration',
            name='organisation_phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='organisation',
            name='company_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='organisation',
            name='motive',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchases',
            name='branch',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='company.branch'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='product_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchases',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='company.projects'),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchase_details',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchases',
            name='purchase_from',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='purchases',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='purchases',
            name='unit_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='assets',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='company.projects'),
        ),
        migrations.AlterField(
            model_name='assets',
            name='type_of_asset',
            field=models.CharField(choices=[('Current Asset', 'Current Asset'), ('Fixed Asset', 'Fixed Asset')], default='Current Asset', max_length=255),
        ),
        migrations.AlterField(
            model_name='debitors',
            name='type_of_debt',
            field=models.CharField(choices=[('Short Term', 'Short Term'), ('Long Term', 'Long Term')], default='Short Term', max_length=255),
        ),
        migrations.AlterField(
            model_name='liabilities',
            name='type_of_liability',
            field=models.CharField(choices=[('Long-term', 'Long-term'), ('Short-term', 'Short-term')], default='Short-term', max_length=255),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_email',
            field=models.EmailField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='organisation_phone_number',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='department',
            field=models.CharField(choices=[('Sales and Marketing', 'Sales and Marketing'), ('IT', 'IT'), ('Finance', 'Finance'), ('Administration and Development', 'Administration and Development'), ('Other', 'Other'), ('Not Applicable', 'Not Applicable')], default='IT', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='occupation',
            field=models.CharField(choices=[('Junior', 'Junior'), ('Customer', 'Customer'), ('Senior', 'Senior'), ('Cashier', 'Cashier'), ('Field Employee', 'Field Employee'), ('Manager', 'Manager'), ('CEO', 'CEO'), ('Software Developer', 'Software Developer'), ('Other', 'Other')], default='Junior', max_length=255),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_branch',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.branch'),
        ),
    ]
