# Generated by Django 4.2 on 2024-08-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_rename_address_companyregistration_personal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='purchaser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='company.staff'),
        ),
    ]
