# Generated by Django 4.2 on 2024-08-27 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_purchases_purchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='debitors',
            name='debt_paid',
            field=models.BooleanField(default=False),
        ),
    ]
