# Generated by Django 4.2 on 2024-08-27 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_debitors_debt_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debitors',
            old_name='debt_paid',
            new_name='debt_paid_status',
        ),
        migrations.AddField(
            model_name='liabilities',
            name='liability_paid_status',
            field=models.BooleanField(default=False),
        ),
    ]
