# Generated by Django 4.2 on 2024-08-27 09:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_rename_debt_paid_debitors_debt_paid_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assets',
            name='date_brought_in',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='assets',
            name='disposed',
            field=models.BooleanField(default=False),
        ),
    ]
