# Generated by Django 4.2 on 2024-08-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_assets_date_brought_in_assets_disposed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='asset_acquisition_date',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project_id',
        ),
        migrations.AddField(
            model_name='staff',
            name='staff_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='company.projects'),
        ),
    ]
