# Generated by Django 4.2 on 2024-08-28 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_rename_company_description_organisation_organisation_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name_email',
            new_name='company_email',
        ),
        migrations.RemoveField(
            model_name='company',
            name='main_branch_location',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
    ]
