# Generated by Django 4.2 on 2024-08-28 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_alter_branch_branch_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liabilities',
            name='projects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='company.projects'),
        ),
    ]
