# Generated by Django 4.2 on 2024-08-30 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_assets_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CEO_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.staff'),
        ),
    ]
