# Generated by Django 4.2 on 2024-08-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_alter_company_ceo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='CEO_name',
        ),
    ]
