# Generated by Django 4.2 on 2024-08-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_remove_company_ceo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CEO_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.staff'),
        ),
    ]
