# Generated by Django 4.2 on 2024-08-30 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_company_ceo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_phone_number',
            new_name='phone_number',
        ),
    ]
