# Generated by Django 4.2 on 2024-08-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_remove_company_ceo_name_remove_company_company_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='CEO_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='company.staff'),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
