# Generated by Django 4.2 on 2024-08-30 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_company_ceo_name_company_email_company_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assets',
            old_name='asset_price',
            new_name='acquistion_price',
        ),
    ]
