# Generated by Django 4.2 on 2024-08-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_assets_asset_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilities',
            name='liability_source',
        ),
        migrations.AddField(
            model_name='liabilities',
            name='details',
            field=models.CharField(default='', max_length=50),
        ),
    ]
