# Generated by Django 4.2 on 2024-08-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_remove_liabilities_liability_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='liabilities',
            name='supplier',
        ),
        migrations.AddField(
            model_name='liabilities',
            name='sources',
            field=models.CharField(choices=[('Individual', 'Individual'), ('Corporate', 'Corporate'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
