# Generated by Django 4.2 on 2024-08-30 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_remove_purchases_product_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchased_item',
            old_name='purchases',
            new_name='purchase',
        ),
    ]
