# Generated by Django 4.2 on 2024-08-30 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_rename_purchases_purchased_item_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchases',
            old_name='purchase_details',
            new_name='details',
        ),
        migrations.RenameField(
            model_name='purchases',
            old_name='purchase_from',
            new_name='source',
        ),
    ]
