# Generated by Django 4.2 on 2024-09-01 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_rename_purchase_details_purchases_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='company.organisation'),
        ),
    ]
