# Generated by Django 4.2 on 2024-09-07 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0051_assets_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='project_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='projects',
            old_name='project_supervisor',
            new_name='supervisor',
        ),
    ]
