# Generated by Django 4.2 on 2024-09-07 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0053_alter_purchases_purchaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchases',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='company.organisation'),
        ),
    ]
