# Generated by Django 4.2 on 2024-09-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0055_alter_purchases_purchaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='branch_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='branch',
            old_name='branch_phone_number',
            new_name='phone_number',
        ),
    ]
