# Generated by Django 4.2 on 2024-09-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0057_purchases_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='purchase_type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Overheads', 'Overheads'), ('Assets', 'Assets')], default='Stock', max_length=255),
        ),
    ]
