# Generated by Django 4.2 on 2024-09-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0058_purchased_item_purchase_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchased_item',
            name='quantity',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='unit_price',
            field=models.FloatField(default=0.0),
        ),
    ]
