# Generated by Django 4.2 on 2024-09-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0059_alter_purchased_item_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('to', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=2)),
                ('details', models.TextField(default='')),
                ('paid', models.BooleanField(default=False)),
            ],
        ),
    ]
