# Generated by Django 4.2 on 2024-09-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0061_alter_loan_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='to',
            new_name='receiver',
        ),
    ]
