# Generated by Django 4.2 on 2024-09-13 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0062_rename_to_loan_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='liabilities',
            name='creditor',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='liabilities',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='liabilities',
            name='phone_number',
            field=models.CharField(default='', max_length=15),
        ),
    ]
