# Generated by Django 4.2 on 2024-09-20 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0064_loan_amount_paid_loan_borrower_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchased_item',
            name='organisation',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_purchased', to='company.organisation'),
        ),
    ]
