# Generated by Django 4.2 on 2024-09-20 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0065_purchased_item_organisation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='monthly_salary',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='purchases',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff',
            name='employment_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchased_item',
            name='purchase_type',
            field=models.CharField(choices=[('Stock', 'Stock'), ('Overheads', 'Overheads'), ('Fixed Assets', 'Fixed Assets'), ('Manufacturing', 'Manufacturing')], default='Stock', max_length=255),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('paid', models.BooleanField(default=False)),
                ('amount_paid', models.FloatField(default=0.0)),
                ('earned_salary', models.FloatField(default=0.0)),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salaries', to='company.staff')),
            ],
        ),
    ]
