# Generated by Django 4.2 on 2024-09-22 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0069_delete_assets_delete_debitor_delete_liabilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditor',
            name='credit_amount_paid',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='company.organisation'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditors', to='company.projects'),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(default='')),
                ('expense_type', models.CharField(choices=[('Debit Interest', 'Debit Interest'), ('Other', 'Other')], default='Debit Interest', max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='company.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='company.projects')),
            ],
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('details', models.TextField(default='')),
                ('expense_type', models.CharField(choices=[('Credit Interest', 'Credit Interest'), ('Other', 'Other')], default='Credit Interest', max_length=50)),
                ('quantity', models.FloatField(default=0.0)),
                ('unit_price', models.FloatField(default=0.0)),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.organisation')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='company.projects')),
            ],
        ),
    ]
