# Generated by Django 4.2 on 2024-09-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0070_creditor_credit_amount_paid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='employees',
        ),
        migrations.AddField(
            model_name='organisation',
            name='tax',
            field=models.FloatField(default=0.0),
        ),
    ]
