# Generated by Django 4.2 on 2024-09-23 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0071_rename_company_name_company_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyRegistration',
            new_name='OrganisationRegistration',
        ),
        migrations.RenameModel(
            old_name='Purchased_Item',
            new_name='PurchasedItem',
        ),
        migrations.DeleteModel(
            name='Loan',
        ),
    ]
