# Generated by Django 4.2 on 2024-09-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0072_rename_companyregistration_organisationregistration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationregistration',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Declined', 'Declined')], default='Pending', max_length=255),
        ),
    ]
