# Generated by Django 4.2 on 2024-09-24 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0074_organisationregistration_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisationregistration',
            name='founder_DOB',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
