# Generated by Django 4.2 on 2024-09-24 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0075_organisationregistration_founder_dob'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organisationregistration',
            old_name='email',
            new_name='founder_email',
        ),
        migrations.RenameField(
            model_name='organisationregistration',
            old_name='headquaters',
            new_name='founder_phone_number',
        ),
        migrations.RenameField(
            model_name='organisationregistration',
            old_name='phone_number',
            new_name='headquarters',
        ),
        migrations.RenameField(
            model_name='organisationregistration',
            old_name='company_description',
            new_name='organisation_description',
        ),
    ]
