# Generated by Django 5.1.2 on 2024-10-31 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0077_rename_headquaters_organisation_headquarters'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='company.organisation'),
        ),
    ]
