# Generated by Django 5.1.2 on 2024-11-24 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0078_branch_organisation'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='monthly_salary',
            field=models.FloatField(default=0.0),
        ),
    ]
