# Generated by Django 5.1.2 on 2024-11-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0080_remove_asset_asset_source_remove_projects_no_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='projects',
            new_name='project',
        ),
    ]
