# Generated by Django 5.1.2 on 2024-11-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0081_rename_projects_asset_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditor',
            old_name='credit_acquisition_date',
            new_name='liability_acquisition_date',
        ),
        migrations.RenameField(
            model_name='creditor',
            old_name='credit_amount',
            new_name='liability_amount',
        ),
        migrations.AlterField(
            model_name='creditor',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='company.organisation'),
        ),
        migrations.AlterField(
            model_name='creditor',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liabilities', to='company.projects'),
        ),
    ]
