# Generated by Django 5.1.2 on 2024-11-24 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0082_rename_credit_acquisition_date_creditor_liability_acquisition_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditor',
            old_name='credit_paid_status',
            new_name='liabiility_paid_status',
        ),
        migrations.RenameField(
            model_name='creditor',
            old_name='credit_type',
            new_name='type_of_liability',
        ),
    ]
