# Generated by Django 5.1.2 on 2024-11-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0083_rename_credit_paid_status_creditor_liabiility_paid_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchases',
            name='tax_percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
