# Generated by Django 5.1.2 on 2024-11-24 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0084_alter_purchases_tax_percentage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='creditor',
            old_name='liabiility_paid_status',
            new_name='liability_paid_status',
        ),
    ]
