# Generated by Django 4.2 on 2024-08-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagesboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('message_id', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('ref', models.CharField(max_length=255)),
                ('receiver', models.CharField(choices=[('All', 'All'), ('User', 'User'), ('Staff', 'Staff'), ('Manager', 'Manager'), ('Executive', 'Executive')], max_length=255)),
                ('urgency', models.CharField(choices=[('!', '!'), ('!!', '!!'), ('!!!', '!!!')], max_length=255)),
            ],
        ),
    ]
