# Generated by Django 4.2 on 2024-08-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_messagesboard_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesboard',
            name='staff',
        ),
    ]
