# Generated by Django 4.2 on 2024-08-20 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_rename_suppliers_liabilities_supplier_and_more'),
        ('messageboard', '0003_remove_messagesboard_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesboard',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.staff'),
        ),
    ]
