# Generated by Django 4.2 on 2024-08-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0004_alter_messagesboard_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagesboard',
            old_name='receiver',
            new_name='receipient',
        ),
    ]
