# Generated by Django 4.2 on 2024-08-24 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('messageboard', '0005_rename_receiver_messagesboard_receipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagesboard',
            name='message_id',
        ),
        migrations.AlterField(
            model_name='messagesboard',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagesboard',
            name='urgency',
            field=models.CharField(choices=[('Enquiry', 'Enquiry'), ('Important', 'Important'), ('Alert', 'Alert')], max_length=255),
        ),
    ]
