# Generated by Django 4.2 on 2024-08-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0007_alter_messagesboard_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagesboard',
            name='ref',
            field=models.CharField(max_length=50),
        ),
    ]
